"""
HOLMESforOMNI Demo — Stage 3: Judge — Requirements Spec
Reads spec from stage 2 output and clarified requirement from stage 1 output.
Writes output to demo/output/03_judge_spec_verdict.md
"""
import json
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.agents.llm_client import call_llm
from src.prompts.prompt_loader import load_prompt

INPUT_SPEC = os.path.join(os.path.dirname(__file__), "output", "02_requirements_spec.md")
INPUT_REQ = os.path.join(os.path.dirname(__file__), "output", "01_clarified_requirement.md")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "output", "03_judge_spec_verdict.md")

def _extract_json(response: str) -> dict:
    start = response.rfind("{")
    if start == -1:
        raise ValueError(f"No JSON block found. Response (first 300): {response[:300]}")
    try:
        return json.loads(response[start:])
    except json.JSONDecodeError as e:
        raise ValueError(f"Malformed JSON: {e}") from e

def _read_section(filepath: str, marker: str, end_marker: str = "---") -> str:
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    start = content.find(marker)
    if start == -1:
        return content.strip()
    start += len(marker)
    end = content.find(end_marker, start)
    return content[start:end].strip() if end != -1 else content[start:].strip()

def main():
    print("\n" + "="*60)
    print("  STAGE 3 — Judge: Requirements Spec")
    print("="*60)

    for f in [INPUT_SPEC, INPUT_REQ]:
        if not os.path.exists(f):
            print(f"[ERROR] Input file not found: {f}")
            return

    with open(INPUT_SPEC, "r", encoding="utf-8") as f:
        requirements_spec = f.read()

    clarified_requirement = _read_section(INPUT_REQ, "## Clarified Requirement")

    print("[Loading prompts...]")
    system_prompt = load_prompt("judge_spec_system")
    user_prompt = load_prompt(
        "judge_spec_user",
        {
            "requirements_spec": requirements_spec,
            "clarified_requirement": clarified_requirement,
        },
    )

    print("[Calling Bedrock — Claude Sonnet 4...]")
    response = call_llm(system_prompt=system_prompt, user_prompt=user_prompt)
    parsed = _extract_json(response)

    verdict = parsed.get("verdict", "UNKNOWN")
    score = parsed.get("score", 0)
    feedback = parsed.get("feedback") or "No issues found."

    output = f"""# Stage 3 — Judge Verdict: Requirements Spec

## Verdict
**{verdict}**

## Score
{score} / 100

## Feedback
{feedback}

---
*Generated by HOLMESforOMNI Stage 3 — Judge: Requirements Spec*
"""

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"[Done] Verdict: {verdict} | Score: {score}/100")
    print(f"[Output written to] {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
