"""
HOLMESforOMNI Demo — Stage 2: Requirements Spec Agent
Reads clarified requirement from stage 1 output.
Writes output to demo/output/02_requirements_spec.md
"""
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.agents.llm_client import call_llm
from src.prompts.prompt_loader import load_prompt, load_context_file

INPUT_FILE = os.path.join(os.path.dirname(__file__), "output", "01_clarified_requirement.md")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "output", "02_requirements_spec.md")

def main():
    print("\n" + "="*60)
    print("  STAGE 2 — Requirements Spec Agent")
    print("="*60)

    if not os.path.exists(INPUT_FILE):
        print(f"[ERROR] Input file not found: {INPUT_FILE}")
        print("Run stage1_qa.py first.")
        return

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        stage1_content = f.read()

    # Extract clarified requirement section from stage 1 output
    marker = "## Clarified Requirement"
    end_marker = "---"
    start = stage1_content.find(marker)
    if start == -1:
        print("[ERROR] Could not find '## Clarified Requirement' in stage 1 output.")
        return
    start += len(marker)
    end = stage1_content.find(end_marker, start)
    clarified_requirement = stage1_content[start:end].strip() if end != -1 else stage1_content[start:].strip()

    print("[Loading prompts and context...]")
    tech_context = load_context_file("tech_context.md")
    system_prompt = load_prompt("requirements_spec_system")
    user_prompt = load_prompt(
        "requirements_spec_user",
        {
            "clarified_requirement": clarified_requirement,
            "tech_context": tech_context,
        },
    )

    print("[Calling Bedrock — Claude Sonnet 4...]")
    requirements_spec = call_llm(system_prompt=system_prompt, user_prompt=user_prompt)

    output = f"""# Stage 2 — Requirements Specification

{requirements_spec}

---
*Generated by HOLMESforOMNI Stage 2 — Requirements Spec Agent*
"""

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"[Done] Spec length: {len(requirements_spec)} chars")
    print(f"[Output written to] {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
