"""
HOLMESforOMNI Demo — Stage 5: Judge — Test Cases
Reads test cases JSON from stage 4 and spec from stage 2.
Writes output to demo/output/05_judge_test_cases_verdict.md
"""
import json
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.agents.llm_client import call_llm
from src.prompts.prompt_loader import load_prompt

INPUT_CASES = os.path.join(os.path.dirname(__file__), "output", "04_test_cases.json")
INPUT_SPEC = os.path.join(os.path.dirname(__file__), "output", "02_requirements_spec.md")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "output", "05_judge_test_cases_verdict.md")

def _extract_json(response: str) -> dict:
    start = response.rfind("{")
    if start == -1:
        raise ValueError(f"No JSON block found. Response (first 300): {response[:300]}")
    try:
        return json.loads(response[start:])
    except json.JSONDecodeError as e:
        raise ValueError(f"Malformed JSON: {e}") from e

def main():
    print("\n" + "="*60)
    print("  STAGE 5 — Judge: Test Cases")
    print("="*60)

    for f in [INPUT_CASES, INPUT_SPEC]:
        if not os.path.exists(f):
            print(f"[ERROR] Input file not found: {f}")
            return

    with open(INPUT_CASES, "r", encoding="utf-8") as f:
        test_cases = json.load(f)

    with open(INPUT_SPEC, "r", encoding="utf-8") as f:
        requirements_spec = f.read()

    test_cases_str = json.dumps(test_cases, indent=2)

    print("[Loading prompts...]")
    system_prompt = load_prompt("judge_test_cases_system")
    user_prompt = load_prompt(
        "judge_test_cases_user",
        {
            "test_cases": test_cases_str,
            "requirements_spec": requirements_spec,
        },
    )

    print("[Calling Bedrock — Claude Sonnet 4...]")
    response = call_llm(system_prompt=system_prompt, user_prompt=user_prompt)
    parsed = _extract_json(response)

    verdict = parsed.get("verdict", "UNKNOWN")
    score = parsed.get("score", 0)
    feedback = parsed.get("feedback") or "No issues found."

    output = f"""# Stage 5 — Judge Verdict: Test Cases

## Verdict
**{verdict}**

## Score
{score} / 100

## Feedback
{feedback}

---
*Generated by HOLMESforOMNI Stage 5 — Judge: Test Cases*
"""

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"[Done] Verdict: {verdict} | Score: {score}/100")
    print(f"[Output written to] {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
