"""
HOLMESforOMNI Demo — Stage 1: QA Interaction Agent
Calls qa_interaction_node logic directly. No graph. No interrupts.
Writes output to demo/output/01_clarified_requirement.md
"""
import json
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.agents.llm_client import call_llm
from src.prompts.prompt_loader import load_prompt, load_context_file

REQUIREMENT = (
    "The OMNI Jurisdiction K Streams job must be updated to reflect new compliance "
    "routing rules. The job consumes messages from the Kafka topic "
    "'omni.jurisdiction.k.raw.events'. Each message payload contains the following "
    "fields: jurisdiction_code (string), transaction_amount (float), account_status "
    "(string, values: ACTIVE, SUSPENDED, CLOSED), and kyc_verified (boolean). "
    "Routing rules: if jurisdiction_code is exactly 'K' AND transaction_amount is "
    "greater than 0.0 AND account_status is 'ACTIVE' AND kyc_verified is true, route "
    "to 'omni.jurisdiction.k.compliant.events'. All other conditions route to "
    "'omni.jurisdiction.k.noncompliant.events'. Edge cases: transaction_amount of "
    "exactly 0.0 is non-compliant. A missing kyc_verified field is non-compliant. "
    "A jurisdiction_code of 'k' (lowercase) is non-compliant. A null account_status "
    "is non-compliant."
)

OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "output", "01_clarified_requirement.md")

def _extract_json(response: str) -> dict:
    start = response.rfind("{")
    if start == -1:
        raise ValueError(f"No JSON block found. Response (first 300): {response[:300]}")
    try:
        return json.loads(response[start:])
    except json.JSONDecodeError as e:
        raise ValueError(f"Malformed JSON: {e}") from e

def main():
    print("\n" + "="*60)
    print("  STAGE 1 — QA Interaction Agent")
    print("="*60)
    print("[Loading prompts and context...]")

    tech_context = load_context_file("tech_context.md")
    system_prompt = load_prompt("qa_interaction_system")
    user_prompt = load_prompt(
        "qa_interaction_user",
        {
            "raw_requirement": REQUIREMENT,
            "clarification_round": "1",
            "engineer_answers": "N/A — demo mode, single pass.",
            "tech_context": tech_context,
        },
    )

    print("[Calling Bedrock — Claude Sonnet 4...]")
    response = call_llm(system_prompt=system_prompt, user_prompt=user_prompt)
    parsed = _extract_json(response)

    confidence = float(parsed.get("confidence_score", 0.0))
    clarified = parsed.get("clarified_requirement", "")

    output = f"""# Stage 1 — Clarified Requirement

## Confidence Score
{confidence:.0%}

## Clarified Requirement
{clarified}

---
*Generated by HOLMESforOMNI Stage 1 — QA Interaction Agent*
"""

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"[Done] Confidence: {confidence:.0%}")
    print(f"[Output written to] {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
