"""
HOLMESforOMNI Demo — Stage 4: Test Case Generation Agent
Reads spec from stage 2 output.
Writes output to demo/output/04_test_cases.md
"""
import json
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.agents.llm_client import call_llm
from src.prompts.prompt_loader import load_prompt, load_context_file

INPUT_FILE = os.path.join(os.path.dirname(__file__), "output", "02_requirements_spec.md")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "output", "04_test_cases.md")
OUTPUT_JSON = os.path.join(os.path.dirname(__file__), "output", "04_test_cases.json")

def _extract_json_array(response: str) -> list:
    response = response.strip()
    start = response.find("[")
    end = response.rfind("]")
    if start == -1 or end == -1:
        raise ValueError(f"No JSON array found. Response (first 300): {response[:300]}")
    try:
        result = json.loads(response[start:end+1])
        if not isinstance(result, list):
            raise ValueError("Parsed JSON is not a list.")
        return result
    except json.JSONDecodeError as e:
        raise ValueError(f"Malformed JSON array: {e}") from e

def main():
    print("\n" + "="*60)
    print("  STAGE 4 — Test Case Generation Agent")
    print("="*60)

    if not os.path.exists(INPUT_FILE):
        print(f"[ERROR] Input file not found: {INPUT_FILE}")
        print("Run stage2_spec.py first.")
        return

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        requirements_spec = f.read()

    print("[Loading prompts and context...]")
    tech_context = load_context_file("tech_context.md")
    system_prompt = load_prompt("test_case_generation_system")
    user_prompt = load_prompt(
        "test_case_generation_user",
        {
            "requirements_spec": requirements_spec,
            "tech_context": tech_context,
        },
    )

    print("[Calling Bedrock — Claude Sonnet 4...]")
    response = call_llm(system_prompt=system_prompt, user_prompt=user_prompt)
    test_cases = _extract_json_array(response)

    # Write JSON for stage 5 to consume
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(test_cases, f, indent=2)

    # Build markdown output
    from collections import Counter
    counts = Counter(c.get("category", "unknown") for c in test_cases)

    rows = "\n".join(
        f"| {c.get('id')} | {c.get('category')} | {c.get('scenario')} | {c.get('expected_outcome')} |"
        for c in test_cases
    )

    output = f"""# Stage 4 — Test Cases

## Summary
| Category | Count |
|---|---|
| Positive | {counts.get('positive', 0)} |
| Negative | {counts.get('negative', 0)} |
| Boundary | {counts.get('boundary', 0)} |
| Malformed | {counts.get('malformed', 0)} |
| **Total** | **{len(test_cases)}** |

## Test Cases

| ID | Category | Scenario | Expected Outcome |
|---|---|---|---|
{rows}

---
*Generated by HOLMESforOMNI Stage 4 — Test Case Generation Agent*
"""

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"[Done] {len(test_cases)} test cases generated")
    print(f"[Output written to] {OUTPUT_FILE}")
    print(f"[JSON written to]   {OUTPUT_JSON}")

if __name__ == "__main__":
    main()
